runtime: nodejs12
env: standard
instance_class: F1

automatic_scaling:
    max_instances: 1

env_variables:
    MYSQL_USER: <USER_NAME>
    MYSQL_PASSWORD: '<PASSWORD>' # Quotes are used to ensure symbols are not interpreted incorrectly
    MYSQL_DATABASE: <DB_SCHAME_NAME>
    INSTANCE_CONNECTION_NAME: /cloudsql/<INSTANCE_CONNECTION_NAME>